version: "3"
services:
  app:
    container_name: fastapi_chat_gpt
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "28000:8000"
    tty: true
    volumes:
      - .:/app


